llvm/clangd-www

- installation.md
See also: https://github.com/clangd/clangd/issues/183
The limitations mentioned were indeed true at some point, 
but haven't been for a while now.
> Remove mention of Eglot limitations now gone

- features.md
A user mentioned that they've read this page and thought clang-tidy wouldn't be enabled unless they say so.
> clang-tidy is enabled by default

- design/indexing.md
> Fix typo in "Indexing"

- design/indexing.md
- llvm-remote-index.md
- remote-index.md
- reduce duplication, particularly between llvm-remote-index and remote-index
- add introduction to remote-index, describing what the feature does
- describe three components of remote-index rather than two (client!)
- clarify support of testing instance (unsupported, not best-effort)
- more direct/concise language (e.g. indexing pipeline -> indexer)
- move a few paragraphs to more closely related sections
- make privacy section of llvm-remote-index specific and remove some subjective language
- broken links fixed (link to *.html, not *.md)
> Tweaks to remote index docs

- config.md
Update config documentation to include ClangTidy docs.
Do not merge until https://reviews.llvm.org/D91029 has landed (or another patch that enables the options).
> Add ClangTidy to Config documentation

- installation.md
'bear make' no longer works. One now needs to use 'bear -- make'
as per official bear documentation:
[https://github.com/rizsotto/Bear/blob/master/README.md](https://github.com/rizsotto/Bear/blob/master/README.md)
> update bear command

- design/threads.md
I'd noticed a missing phrase while reading through the clangd design docs, and figured I'd propose a quick fix. 
@sam-mccall, looks like you last committed to these docs, and you were the one nice enough to point me to them, so I'm going to tag you :)  At the same time, a hearty "hi" and "thank you" from an ex-Googler.
> Proposed fix for typo in clangd threading docs

- config.md
This can mislead people into thinking flags don't need to be comma separated
> Fix CompileFlags:Add example not including a comma

- extensions.md
There is a typo in the tag for v12 resulting in the tag not being displayed
> Fix AST and MemoryUsage extensions not listing clangd-12

- config.md
Add `Diagnostic` block to config and move the `ClangTidy` under there.
Also tag the block as version 12 to save confusion.
> Add Diagnostics Block to config documentation

- _data/navigation.yml
- llvm-remote-index.md
- remote-index.md
Currently points to the now removed master branch, update it to point to main.
> Fix github source code link

- config.md
Just started working with clangd and copied the ClangTidy config example from this page.
I then got the following error message:
Compared to the Index section, the diagnostics section misses the `Diagnostics` key.
Hope this little fix helps others in the future.
> add Diagnostics token to ClangTidy example configs

- config.md
Fixes https://github.com/clangd/clangd/issues/650
This is the last entry that is untagged going off the premise that any header tagged with a version should indicate that all its subkeys are also tagged with the same version.
> Add clangd-12 tag to Index->External in config

- _data/navigation.yml
- llvm-remote-index.md
* Add production server address
* Remove mentions of the service being experimental
* Add Remote Index pages to the navbar for better visibility and feature
discovery (it's almost impossible to find otherwise)
> Update remote index documentation

- _data/navigation.yml
- _layouts/default.html
- styles.css
The idea here is to make it conceptually easier/cheaper to add new pages without affecting the existing nav by "burying" them under sections that are only expanded after being selected.
This is used for the design docs but the mechanism should also be used for user-facing "guides" that can be fairly niche and don't have a good home in the current design.
At least for now these child-pages are accessible through nav only on desktop, so mobile still relies on finding them from the "landing page".
Preview: https://sam-mccall.github.io/clangd-www/
> Add support for child pages in nav (desktop only). Used for design/

- _config.yml
- _data/navigation.yml
- design/remote-index.md
- llvm-remote-index.md
Also set up redirections so we don't break existing links
(TODO: split out user-facing part into guides, and inline the LLVM
remote index page)
> Move remote index docs under design

- installation.md
The latest release of LLVM is 12.0 now, so we could also update the latest version of clangd to 12.0 in installation.md
> Update latest version to 12.0 in installation.md

- installation.md
This doc lists ways of getting compilation databases out of some popular build systems for use with clangd. 
We built such a way for Bazel and just released it after a bunch of requests on GitHub. I'd [proposed adding it to the llvm compile_commands.json docs](https://reviews.llvm.org/D114213), and folks suggested we also add it here.
Thanks for your consideration--and the most wonderful of tools.
> Compilation Database: Point Bazel users to a solution

- faq.md
The answer no longer recommends using the CompilationDatabase key,
as this was discovered not to be suitable for this purpose.
See https://github.com/clangd/clangd/discussions/907
> FAQ: Revise answer to question about headers outside project directory

- config.md
While creating a new clang-tidy check or using most of the available clang-tidy check modules,
it could be useful to activate all possible checks and remove a few unwanted ones.
By doing so, it seems that this only works with the clangd configuration style (config.yaml or .clangd)
by wrapping `*` in single quotes, like it would be done in a .clang-tidy file.
```
Diagnostics:
ClangTidy:
Add: '*'
```
The clangd documentation shows that `Add: modernize*` is a valid configuration.
In my opinion, this implies that `Add: *` is also valid, which is not the case.
It generates a "Got empty alias or anchor" error, which I believe comes from the YAMLParser.cpp file.
To make this edge case clearer, I recommend updating the configuration page as shown in this pull request.
> change clang-tidy config

- design/indexing.md
- design/remote-index.md
- guides/remote-index.md
> Redirect remote-index links to Guides instead of Design

- faq.md
The example used -I=path as an compile flag to add, but -I
does not support '=' as a separator.
Fixes https://github.com/clangd/clangd/issues/1150
> Fix an incorrect example in the FAQ

- config.md
This is no longer the case as diagnostics are emitted using LSP methods and show up in the editor.
> Remove line about config errors showing up in logs.

- troubleshooting.md
I was reading the troubleshooting guide for getting clangd to work,
and I was momentarily confused by the compile-flags since they differ from the --help menu.
> Fix Troubleshooting.md compile-flags typos

- guides/system-headers.md
rename `compile\_commadns..json` to `compile\_commands.json`
> Typo fixed in system-headers.md

- extensions.md
corresponding patch: https://reviews.llvm.org/D137894
relevant issue: https://github.com/clangd/clangd/issues/177
> Add documentation for Reference Container extension

- config.md
--include-dir is not a supported flag, --include-directory is
> Fix incorrect clang flag in example

- guides/include-cleaner.md
- styles.css
The feature was added in https://reviews.llvm.org/D143496, which was merged after the 16.x branch cut and was not backported to the 16.x branch, thus it's only available in clangd 17.
> Correct version info for 'missing includes' feature

- config.md
I deliberately omitted ClangTidy --> FastCheckFilter since that's only going to be in clangd 18.
> Add missing documentation for config options in clangd 17 or earlier

- troubleshooting.md
Based on experience answering hundreds of users questions, users don't tend to think of MinGW as "unusual" or a "cross-compiler", but it does seem to require use of --query-driver to work well.
> Explicitly call out MinGW as needing --query-driver

- faq.md
At https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-include-file, you can see that only `--include` supports being used like `--include=foo.h`. `-include` can only be used like `-includefoo.h`, and so trying to follow the instructions and use `-include=*` doesn't do anything.
I'm kind of surprised that I didn't get any errors trying to use `-include=*`, `clangd` seems to be suppressing them or something.
> Fix syntax for including individual header in FAQ

- config.md
- design/include-cleaner.md
- styles.css
Docs for llvm/llvm-project#87208
> Document AnalyzeAngledIncludes, update info about standard library includes

- installation.md
there is no initialization_options field in lspconfig
> docs: typo on lspconfig init_options

- installation.md
> docs: remove unnecessary config in lspconfig

- installation.md
sry for typo there should be `fallbackFlags`
> docs: fix typo

- config.md
- styles.css
This PR depends on https://github.com/llvm/llvm-project/pull/129459 landing.
> Add BuiltinHeaders to config docs

- config.md
Add documentation for this feature: llvm/llvm-project#137613
> Document CodePatterns config option

- extensions.md
Once https://github.com/llvm/llvm-project/pull/142903 is merged and a new version of clangd is released, the utf8 offsets extension will be deprecated. This PR updates the documentation to mark this extension as deprecated.
> Mark UTF-8 offsets extension as deprecated

- installation.md
Some package managers still ship the older Bear release (2.4.x). For the older version the correct usage for Bear is as follows:
```
bear make
```
Note: There is no `--` sign
This has also been added in the official Bear [Readme](https://github.com/rizsotto/Bear)
Updated the installation.md to show the correct usage for both major releases of Bear (2.4.x & 3.0.x)
> Update installation.md to show correct usage of Bear (2.4.x)

- config.md
- styles.css
The `Documentation` config option was added with llvm/llvm-project#140498 which is related to clangd/clangd#529.
> Add documentation for the config option "Documentation"
