llvm/clangd-www

llvm-remote-index.md
remote-index.md

+ also small formatting changes

Minor Markdown style fixes & wording improvements

---

config.md

This can be confusing to some of our users otherwise.
Resolves: https://github.com/clangd/clangd/issues/735

Add a note about obsolete .clangd directory -> .clangd config file transition

---

installation.md

Update youcompleteme link

---

extensions.md

Fixes https://github.com/clangd/clangd/issues/808

Document clangd's type hierarchy extension

---

faq.md

This starts FAQ with the (most important) entries to verify the format
and structure. More QAs coming in subsequent patches.
Related issue: https://github.com/llvm/clangd-www/issues/33

Add FAQ with some of the (most important) questions

---

guides/system-headers.md

Fix word spelling errors

---

extensions.md
styles.css

See updates on https://github.com/clangd/clangd/issues/313

Document inlay hints for clangd 14

---

_layouts/default.html
scripts.js
styles.css

Fixes https://github.com/llvm/clangd-www/issues/47

Add anchor links (self links) to headers within pages.

---

config.md

Fix link from Configuration to Remote Index guide

---

guides/include-cleaner.md

Based on [Stackoverflow answer](https://stackoverflow.com/a/27071588). I have tested it locally with Jekyll and it seems to work. However, I am not aware if this repo uses Markdown linter of some sort and how well such line breaking technique will be seen by linters.

Fix IWYU Pragmas documentation link

---

installation.md

Update installation instructions to reflect that the latest version is 15.0

---

config.md

solve issue <https://github.com/clangd/clangd/issues/1472>. add Designator configuration under InlayHints. And add Desgnator discription.

add Designator configuration under InlayHints.

---

troubleshooting.md

See also: https://github.com/clangd/clangd/issues/1654#issuecomment-1573415515

Add note on passing C++ compiler to --query-driver

---

design/include-cleaner.md

Correct typo

---

features.md

Fix incorrect LSP Name for InactiveCode (llvm/llvm-project#78156)

---

troubleshooting.md

Added clarification regarding --query-commands

---

installation.md

feat(installation): add coc-clangd and nvim builtin LSP client

---

features.md

As discussed in https://github.com/clangd/clangd/issues/2127

Mention experimental modules support

---

installation.md

docs: more details usage in neovim

---

config.md

Document potential feature from https://github.com/llvm/llvm-project/pull/155105

Document `Hover.MacroContentsLimit` option
